config/routes.rb
SimpleApi::Application.routes.draw do
  resources :group_requests

  resources :group_members

  resources :groups

  resources :group_types

  resources :users

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :group_type
end

app/models/group_type.rb
class GroupType < ActiveRecord::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    render json: @groups
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    render json: @group
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :group_type_id, :owner_user_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="field">
    <%= f.label :leavable %><br>
    <%= f.check_box :leavable %>
  </div>
  <div class="field">
    <%= f.label :member_list %><br>
    <%= f.check_box :member_list %>
  </div>
  <div class="field">
    <%= f.label :group_type_id %><br>
    <%= f.text_field :group_type_id %>
  </div>
  <div class="field">
    <%= f.label :owner_user_id %><br>
    <%= f.number_field :owner_user_id %>
  </div>
  <div class="field">
    <%= f.label :app_sponsor_id %><br>
    <%= f.number_field :app_sponsor_id %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.number_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br>
    <%= f.number_field :updated_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Visible</th>
      <th>Leavable</th>
      <th>Member list</th>
      <th>Group type</th>
      <th>Owner user</th>
      <th>App sponsor</th>
      <th>Created by</th>
      <th>Updated by</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= group.visible %></td>
        <td><%= group.leavable %></td>
        <td><%= group.member_list %></td>
        <td><%= group.group_type %></td>
        <td><%= group.owner_user_id %></td>
        <td><%= group.app_sponsor_id %></td>
        <td><%= group.created_by %></td>
        <td><%= group.updated_by %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @group.visible %>
</p>

<p>
  <strong>Leavable:</strong>
  <%= @group.leavable %>
</p>

<p>
  <strong>Member list:</strong>
  <%= @group.member_list %>
</p>

<p>
  <strong>Group type:</strong>
  <%= @group.group_type %>
</p>

<p>
  <strong>Owner user:</strong>
  <%= @group.owner_user_id %>
</p>

<p>
  <strong>App sponsor:</strong>
  <%= @group.app_sponsor_id %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @group.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @group.updated_by %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>