config/routes.rb
SimpleApi::Application.routes.draw do
  resources :group_requests

  resources :group_members

  resources :groups

  resources :group_types

  resources :users

end

app/models/group_request.rb
class GroupRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/controllers/group_requests_controller.rb
class GroupRequestsController < ApplicationController
  before_action :set_group_request, only: [:show, :edit, :update, :destroy]

  # GET /group_requests
  # GET /group_requests.json
  def index
    @group_requests = GroupRequest.all
  end

  # GET /group_requests/1
  # GET /group_requests/1.json
  def show
  end

  # GET /group_requests/new
  def new
    @group_request = GroupRequest.new
  end

  # GET /group_requests/1/edit
  def edit
  end

  # POST /group_requests
  # POST /group_requests.json
  def create
    @group_request = GroupRequest.new(group_request_params)

    respond_to do |format|
      if @group_request.save
        format.html { redirect_to @group_request, notice: 'Group request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @group_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_requests/1
  # PATCH/PUT /group_requests/1.json
  def update
    respond_to do |format|
      if @group_request.update(group_request_params)
        format.html { redirect_to @group_request, notice: 'Group request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_requests/1
  # DELETE /group_requests/1.json
  def destroy
    @group_request.destroy
    respond_to do |format|
      format.html { redirect_to group_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_request
      @group_request = GroupRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_request_params
      params.require(:group_request).permit(:user_id, :group_id, :pre_auth, :approved, :created_by, :updated_by)
    end
end

app/helpers/group_requests_helper.rb
module GroupRequestsHelper
end

app/views/group_requests/_form.html.erb
<%= form_for(@group_request) do |f| %>
  <% if @group_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_request.errors.count, "error") %> prohibited this group_request from being saved:</h2>

      <ul>
      <% @group_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.text_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :pre_auth %><br>
    <%= f.check_box :pre_auth %>
  </div>
  <div class="field">
    <%= f.label :approved %><br>
    <%= f.check_box :approved %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.number_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br>
    <%= f.number_field :updated_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/group_requests/edit.html.erb
<h1>Editing group_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_request %> |
<%= link_to 'Back', group_requests_path %>

app/views/group_requests/index.html.erb
<h1>Listing group_requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Group</th>
      <th>Pre auth</th>
      <th>Approved</th>
      <th>Created by</th>
      <th>Updated by</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @group_requests.each do |group_request| %>
      <tr>
        <td><%= group_request.user %></td>
        <td><%= group_request.group %></td>
        <td><%= group_request.pre_auth %></td>
        <td><%= group_request.approved %></td>
        <td><%= group_request.created_by %></td>
        <td><%= group_request.updated_by %></td>
        <td><%= link_to 'Show', group_request %></td>
        <td><%= link_to 'Edit', edit_group_request_path(group_request) %></td>
        <td><%= link_to 'Destroy', group_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group request', new_group_request_path %>

app/views/group_requests/new.html.erb
<h1>New group_request</h1>

<%= render 'form' %>

<%= link_to 'Back', group_requests_path %>

app/views/group_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @group_request.user %>
</p>

<p>
  <strong>Group:</strong>
  <%= @group_request.group %>
</p>

<p>
  <strong>Pre auth:</strong>
  <%= @group_request.pre_auth %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @group_request.approved %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @group_request.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @group_request.updated_by %>
</p>

<%= link_to 'Edit', edit_group_request_path(@group_request) %> |
<%= link_to 'Back', group_requests_path %>