config/routes.rb
SimpleApi::Application.routes.draw do
  resources :group_requests

  resources :group_members

  resources :groups

  resources :group_types

  resources :users

end

app/controllers/group_types_controller.rb
class GroupTypesController < ApplicationController
  before_action :set_group_type, only: [:show, :edit, :update, :destroy]

  # GET /group_types
  # GET /group_types.json
  def index
    @group_types = GroupType.all
  end

  # GET /group_types/1
  # GET /group_types/1.json
  def show
  end

  # GET /group_types/new
  def new
    @group_type = GroupType.new
  end

  # GET /group_types/1/edit
  def edit
  end

  # POST /group_types
  # POST /group_types.json
  def create
    @group_type = GroupType.new(group_type_params)

    respond_to do |format|
      if @group_type.save
        format.html { redirect_to @group_type, notice: 'Group type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @group_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_types/1
  # PATCH/PUT /group_types/1.json
  def update
    respond_to do |format|
      if @group_type.update(group_type_params)
        format.html { redirect_to @group_type, notice: 'Group type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_types/1
  # DELETE /group_types/1.json
  def destroy
    @group_type.destroy
    respond_to do |format|
      format.html { redirect_to group_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_type
      @group_type = GroupType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_type_params
      params.require(:group_type).permit(:name, :description, :created_by, :updated_by)
    end
end

app/helpers/group_types_helper.rb
module GroupTypesHelper
end

app/views/group_types/_form.html.erb
<%= form_for(@group_type) do |f| %>
  <% if @group_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_type.errors.count, "error") %> prohibited this group_type from being saved:</h2>

      <ul>
      <% @group_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.number_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br>
    <%= f.number_field :updated_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/group_types/edit.html.erb
<h1>Editing group_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_type %> |
<%= link_to 'Back', group_types_path %>

app/views/group_types/index.html.erb
<h1>Listing group_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Created by</th>
      <th>Updated by</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @group_types.each do |group_type| %>
      <tr>
        <td><%= group_type.name %></td>
        <td><%= group_type.description %></td>
        <td><%= group_type.created_by %></td>
        <td><%= group_type.updated_by %></td>
        <td><%= link_to 'Show', group_type %></td>
        <td><%= link_to 'Edit', edit_group_type_path(group_type) %></td>
        <td><%= link_to 'Destroy', group_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group type', new_group_type_path %>

app/views/group_types/new.html.erb
<h1>New group_type</h1>

<%= render 'form' %>

<%= link_to 'Back', group_types_path %>

app/views/group_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group_type.description %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @group_type.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @group_type.updated_by %>
</p>

<%= link_to 'Edit', edit_group_type_path(@group_type) %> |
<%= link_to 'Back', group_types_path %>